// DO NOT MODIFY DIRECTLY
// This file was generated by the tools.rem.GenerateAst
package org.rem.parser.ast;

import org.rem.parser.Token;
import java.util.List;

public abstract class Typed extends AST {
  public abstract<T> T accept(Visitor<T> visitor);
  public abstract void accept(VoidVisitor visitor);

  @Override public String astName() {
    return "typed";
  }

  public interface Visitor<T> {
    T visitVoidTyped(Void typed);
    T visitIdTyped(Id typed);
    T visitArrayTyped(Array typed);
    T visitVectorTyped(Vector typed);
    T visitMapTyped(Map typed);
    T visitTyped(Typed typed);
  }


  public interface VoidVisitor {
    void visitVoidTyped(Void typed);
    void visitIdTyped(Id typed);
    void visitArrayTyped(Array typed);
    void visitVectorTyped(Vector typed);
    void visitMapTyped(Map typed);
    void visitTyped(Typed typed);
  }

  public static class Void extends Typed {
    public Void() {
    }

    public <T> T accept(Visitor<T> visitor) {
      return visitor.visitVoidTyped(this);
    }

    public void accept(VoidVisitor visitor) {
      visitor.visitVoidTyped(this);
    }

    @Override public String astName() {
      return "void typed";
    }
  }

  public static class Id extends Typed {
    public final Expression.Identifier name;

    public Id(Expression.Identifier name) {
      this.name = name;
    }

    public <T> T accept(Visitor<T> visitor) {
      return visitor.visitIdTyped(this);
    }

    public void accept(VoidVisitor visitor) {
      visitor.visitIdTyped(this);
    }

    @Override public String astName() {
      return "id typed";
    }
  }

  public static class Array extends Typed {
    public final Typed type;
    public final int size;

    public Array(Typed type, int size) {
      this.type = type;
      this.size = size;
    }

    public <T> T accept(Visitor<T> visitor) {
      return visitor.visitArrayTyped(this);
    }

    public void accept(VoidVisitor visitor) {
      visitor.visitArrayTyped(this);
    }

    @Override public String astName() {
      return "array typed";
    }
  }

  public static class Vector extends Typed {
    public final Typed type;

    public Vector(Typed type) {
      this.type = type;
    }

    public <T> T accept(Visitor<T> visitor) {
      return visitor.visitVectorTyped(this);
    }

    public void accept(VoidVisitor visitor) {
      visitor.visitVectorTyped(this);
    }

    @Override public String astName() {
      return "vector typed";
    }
  }

  public static class Map extends Typed {
    public final Typed keyType;
    public final Typed valueType;

    public Map(Typed keyType, Typed valueType) {
      this.keyType = keyType;
      this.valueType = valueType;
    }

    public <T> T accept(Visitor<T> visitor) {
      return visitor.visitMapTyped(this);
    }

    public void accept(VoidVisitor visitor) {
      visitor.visitMapTyped(this);
    }

    @Override public String astName() {
      return "map typed";
    }
  }
}
